[package]
name = "bsq"
version = "0.1.0"
authors = ["Abe Augustijn <abe.augustijn@hotmail.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
